[phases.setup]
nixPkgs = ["nodejs_20", "python3", "gcc", "gnumake"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = ["mkdir -p ./data", "npm run build"]

[start]
cmd = "DB_DIR=./data npm run start"
